### ISSUE TITLE
No module named 'disutils' during installation. 

### ISSUE THREAD

**Issue by BenjaminJorgensen** [Aylur/ags#539]
Hi, during installation it seems like the GUtils sub-module tries to call 'distutils' even though it isn't installed in the environment. This error occurs both when installing via `yay` and from source. I also have `setuptools` installed global which I believe is where the module comes from. All system packages are up to date to the latest version as far as I'm aware. 

Input:
```
sudo pacman -S typescript npm meson gjs gtk3 gtk-layer-shell gnome-bluetooth-3.0 upower networkmanager gobject-introspection libdbusmenu-gtk3 libsoup3
git clone --recursive https://github.com/Aylur/ags.git
cd ags
npm install
meson setup build
meson install -C build
```

```[12/22] Generating subprojects/gutils/GUtils-1.0.gir with a custom command (wrapped by meson to set env)
FAILED: subprojects/gutils/GUtils-1.0.gir 
env PKG_CONFIG_PATH=/path/ags/build/meson-uninstalled PKG_CONFIG=/usr/bin/pkg-config CC=cc /usr/bin/g-ir-scanner --quiet --no-libtool --namespace=GUtils --nsversion=1.0 --warn-all --output subprojects/gutils/GUtils-1.0.gir -I/path/ags/subprojects/gutils -I/path/ags/build/subprojects/gutils --filelist=/path/ags/build/subprojects/gutils/libgutils.so.p/GUtils_1.0_gir_filelist --include=GObject-2.0 --include=Gio-2.0 --symbol-prefix=gutils --identifier-prefix=GUtils --cflags-begin -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/sysprof-6 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/security -I/usr/include/gobject-introspection-1.0 --cflags-end --add-include-path=/usr/share/gir-1.0 -L/path/ags/build/subprojects/gutils --library gutils -lgobject-2.0 -lglib-2.0 -lgio-2.0 -lpam -lgirepository-1.0
Traceback (most recent call last):
  File "/usr/bin/g-ir-scanner", line 99, in <module>
    from giscanner.utils import dll_dirs
  File "/usr/lib/gobject-introspection/giscanner/utils.py", line 385, in <module>
    import distutils.cygwinccompiler
ModuleNotFoundError: No module named 'distutils'```

**Comment by shivambegin** [comment]
i got the same error, can't install ags

**Comment by imbypass** [comment]
'distutils' was deprecated in Python 3.12; I found success in installing 'pyenv' and using Python 3.10.4 to build ags from source.

**Comment by vafu** [comment]
this is still an issue, AUR build seems to be broken if you have 3.11+ installed
@kotontrion

**Comment by kotontrion** [comment]
https://github.com/Aylur/ags/issues/554
