### ISSUE TITLE
Error installing AGS on Arch Linux.

### ISSUE THREAD

**Issue by CleverFlare** [Aylur/ags#554]
I've recently learned about AGS and I think it's an incredibly exciting project. I wanted to try it out as I am already a Web Developer with experience in JavaScript/TypeScript. However, installing it either using the AUR or building from the source doesn't complete successfully for some reason.

Here are the logs I get when trying to run `meson install -C build`:
```
ninja: Entering directory `/home/flare/ags/build'
[3/22] Compiling C object subprojects/gutils/libgutils.so.p/pam.c.o
../subprojects/gutils/pam.c: In function ‘auth_thread’:
../subprojects/gutils/pam.c:50:34: warning: unused parameter ‘object’ [-Wunused-parameter]
   50 |                   gpointer       object,
      |                   ~~~~~~~~~~~~~~~^~~~~~
../subprojects/gutils/pam.c:52:34: warning: unused parameter ‘cancellable’ [-Wunused-parameter]
   52 |                   GCancellable  *cancellable) {
      |                   ~~~~~~~~~~~~~~~^~~~~~~~~~~
[6/22] Generating subprojects/gutils/GUtils-1.0.gir with a custom command (wrapped by meson to set env)
FAILED: subprojects/gutils/GUtils-1.0.gir 
env PKG_CONFIG_PATH=/home/flare/ags/build/meson-uninstalled PKG_CONFIG=/usr/bin/pkg-config CC=cc /usr/bin/g-ir-scanner --quiet --no-libtool --namespace=GUtils --nsversion=1.0 --warn-all --output subprojects/gutils/GUtils-1.0.gir -I/home/flare/ags/subprojects/gutils -I/home/flare/ags/build/subprojects/gutils --filelist=/home/flare/ags/build/subprojects/gutils/libgutils.so.p/GUtils_1.0_gir_filelist --include=GObject-2.0 --include=Gio-2.0 --symbol-prefix=gutils --identifier-prefix=GUtils --cflags-begin -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/sysprof-6 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/security -I/usr/include/gobject-introspection-1.0 --cflags-end --add-include-path=/usr/share/gir-1.0 -L/home/flare/ags/build/subprojects/gutils --library gutils -lgobject-2.0 -lglib-2.0 -lgio-2.0 -lpam -lgirepository-1.0
Traceback (most recent call last):
  File "/usr/bin/g-ir-scanner", line 99, in <module>
    from giscanner.utils import dll_dirs
  File "/usr/lib/gobject-introspection/giscanner/utils.py", line 385, in <module>
    import distutils.cygwinccompiler
ModuleNotFoundError: No module named 'distutils'
[9/22] Compiling C object subprojects/gvc/libgvc.so.p/gvc-mixer-card.c.o
../subprojects/gvc/gvc-mixer-card.c: In function ‘_pa_context_set_card_profile_by_index_cb’:
../subprojects/gvc/gvc-mixer-card.c:200:77: warning: unused parameter ‘context’ [-Wunused-parameter]
  200 | _pa_context_set_card_profile_by_index_cb (pa_context                       *context,
      |                                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~
[15/22] Compiling C object subprojects/gvc/libgvc.so.p/gvc-mixer-stream.c.o
../subprojects/gvc/gvc-mixer-stream.c: In function ‘on_channel_map_volume_changed’:
../subprojects/gvc/gvc-mixer-stream.c:370:48: warning: unused parameter ‘channel_map’ [-Wunused-parameter]
  370 | on_channel_map_volume_changed (GvcChannelMap  *channel_map,
      |                                ~~~~~~~~~~~~~~~~^~~~~~~~~~~
../subprojects/gvc/gvc-mixer-stream.c: In function ‘gvc_mixer_stream_real_change_port’:
../subprojects/gvc/gvc-mixer-stream.c:817:52: warning: unused parameter ‘stream’ [-Wunused-parameter]
  817 | gvc_mixer_stream_real_change_port (GvcMixerStream *stream,
      |                                    ~~~~~~~~~~~~~~~~^~~~~~
../subprojects/gvc/gvc-mixer-stream.c:818:52: warning: unused parameter ‘port’ [-Wunused-parameter]
  818 |                                    const char     *port)
      |                                    ~~~~~~~~~~~~~~~~^~~~
../subprojects/gvc/gvc-mixer-stream.c: In function ‘gvc_mixer_stream_real_push_volume’:
../subprojects/gvc/gvc-mixer-stream.c:824:52: warning: unused parameter ‘stream’ [-Wunused-parameter]
  824 | gvc_mixer_stream_real_push_volume (GvcMixerStream *stream, gpointer *op)
      |                                    ~~~~~~~~~~~~~~~~^~~~~~
../subprojects/gvc/gvc-mixer-stream.c:824:70: warning: unused parameter ‘op’ [-Wunused-parameter]
  824 | gvc_mixer_stream_real_push_volume (GvcMixerStream *stream, gpointer *op)
      |                                                            ~~~~~~~~~~^~
../subprojects/gvc/gvc-mixer-stream.c: In function ‘gvc_mixer_stream_real_change_is_muted’:
../subprojects/gvc/gvc-mixer-stream.c:830:56: warning: unused parameter ‘stream’ [-Wunused-parameter]
  830 | gvc_mixer_stream_real_change_is_muted (GvcMixerStream *stream,
      |                                        ~~~~~~~~~~~~~~~~^~~~~~
../subprojects/gvc/gvc-mixer-stream.c:831:56: warning: unused parameter ‘is_muted’ [-Wunused-parameter]
  831 |                                        gboolean        is_muted)
      |                                        ~~~~~~~~~~~~~~~~^~~~~~~~
[16/22] Compiling C object subprojects/gvc/libgvc.so.p/gvc-mixer-control.c.o
../subprojects/gvc/gvc-mixer-control.c: In function ‘gvc_mixer_control_stream_restore_cb’:
../subprojects/gvc/gvc-mixer-control.c:170:50: warning: unused parameter ‘c’ [-Wunused-parameter]
  170 | gvc_mixer_control_stream_restore_cb (pa_context *c,
      |                                      ~~~~~~~~~~~~^
../subprojects/gvc/gvc-mixer-control.c: In function ‘listify_hash_values_hfunc’:
../subprojects/gvc/gvc-mixer-control.c:738:37: warning: unused parameter ‘key’ [-Wunused-parameter]
  738 | listify_hash_values_hfunc (gpointer key,
      |                            ~~~~~~~~~^~~
../subprojects/gvc/gvc-mixer-control.c: In function ‘on_default_source_port_notify’:
../subprojects/gvc/gvc-mixer-control.c:936:48: warning: unused parameter ‘pspec’ [-Wunused-parameter]
  936 |                                GParamSpec     *pspec,
      |                                ~~~~~~~~~~~~~~~~^~~~~
../subprojects/gvc/gvc-mixer-control.c: In function ‘on_default_sink_port_notify’:
../subprojects/gvc/gvc-mixer-control.c:1008:46: warning: unused parameter ‘pspec’ [-Wunused-parameter]
 1008 |                              GParamSpec     *pspec,
      |                              ~~~~~~~~~~~~~~~~^~~~~
../subprojects/gvc/gvc-mixer-control.c: In function ‘_stream_has_name’:
../subprojects/gvc/gvc-mixer-control.c:1085:35: warning: unused parameter ‘key’ [-Wunused-parameter]
 1085 | _stream_has_name (gpointer        key,
      |                   ~~~~~~~~~~~~~~~~^~~
../subprojects/gvc/gvc-mixer-control.c: In function ‘match_stream_with_devices’:
../subprojects/gvc/gvc-mixer-control.c:1254:46: warning: comparison of integer expressions of different signedness: ‘gint’ {aka ‘int’} and ‘guint’ {aka ‘unsigned int’} [-Wsign-compare]
 1254 |                         if (device_stream_id == stream_id) {
      |                                              ^~
../subprojects/gvc/gvc-mixer-control.c: In function ‘free_priv_port_names’:
../subprojects/gvc/gvc-mixer-control.c:2243:43: warning: unused parameter ‘control’ [-Wunused-parameter]
 2243 | free_priv_port_names (GvcMixerControl    *control)
      |                       ~~~~~~~~~~~~~~~~~~~~^~~~~~~
../subprojects/gvc/gvc-mixer-control.c: In function ‘gvc_mixer_control_set_headset_port’:
../subprojects/gvc/gvc-mixer-control.c:2256:59: warning: unused parameter ‘id’ [-Wunused-parameter]
 2256 |                                     guint                 id,
      |                                     ~~~~~~~~~~~~~~~~~~~~~~^~
../subprojects/gvc/gvc-mixer-control.c:2257:59: warning: unused parameter ‘choice’ [-Wunused-parameter]
 2257 |                                     GvcHeadsetPortChoice  choice)
      |                                     ~~~~~~~~~~~~~~~~~~~~~~^~~~~~
../subprojects/gvc/gvc-mixer-control.c: In function ‘_pa_context_get_server_info_cb’:
../subprojects/gvc/gvc-mixer-control.c:2813:55: warning: unused parameter ‘context’ [-Wunused-parameter]
 2813 | _pa_context_get_server_info_cb (pa_context           *context,
      |                                 ~~~~~~~~~~~~~~~~~~~~~~^~~~~~~
../subprojects/gvc/gvc-mixer-control.c: In function ‘remove_event_role_stream’:
../subprojects/gvc/gvc-mixer-control.c:2829:44: warning: unused parameter ‘control’ [-Wunused-parameter]
 2829 | remove_event_role_stream (GvcMixerControl *control)
      |                           ~~~~~~~~~~~~~~~~~^~~~~~~
../subprojects/gvc/gvc-mixer-control.c: In function ‘req_update_server_info’:
../subprojects/gvc/gvc-mixer-control.c:2940:42: warning: unused parameter ‘index’ [-Wunused-parameter]
 2940 |                         int              index)
      |                         ~~~~~~~~~~~~~~~~~^~~~~
../subprojects/gvc/gvc-mixer-control.c: In function ‘_pa_context_subscribe_cb’:
../subprojects/gvc/gvc-mixer-control.c:3280:56: warning: unused parameter ‘context’ [-Wunused-parameter]
 3280 | _pa_context_subscribe_cb (pa_context                  *context,
      |                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~
[17/22] Generating src/typescript-compile with a custom command
ninja: build stopped: subcommand failed.
Could not rebuild /home/flare/ags/build
```

**Comment by kotontrion** [comment]
```
Traceback (most recent call last): 
    File "/usr/bin/g-ir-scanner", line 99, in <module>
       from giscanner.utils import dll_dirs
    File "/usr/lib/gobject-introspection/giscanner/utils.py", line 385, in <module>
       import distutils.cygwinccompiler
ModuleNotFoundError: No module named 'distutils'
```

This is a common issue if you have something active that messes with the python environment, like a virtualenv.

**Comment by CleverFlare** [comment]
@kotontrion 
I made a quick search and seems like the module `distutils` was removed in the 3.12 version of Python. I can't downgrade as parts of my system my break due to their reliance on Python, perhaps that version specifically.
I wonder if there is any workaround for the time being?

**Comment by kotontrion** [comment]
`distutils` was removed in python 3.12, but was added in the `python-setuptools` package, which is a dependency of `gobject-introspection`

**Comment by CleverFlare** [comment]
@kotontrion 
I've initially installed the package without using any virtual environment at all. I ensured all the dependencies where properly installed. I've even installed them individually. It's only when you pointed out the fact that it's caused by `distutils` I started to look into it and tried using a virtual environment in order to use a later version of Python. This is perhaps the first time I ever use a virtual environment after my recent installation of system.
I think I've currently tried out every possible solution to solve this problem; but it persists. I'm confused at this point about what I could be doing wrong, honestly.

**Comment by kotontrion** [comment]
Having a virtual environment active is the only reason for this issue i can currently think of. So are you really sure? Having something like conda installed can mess things up as well.

whats the output of `type python`?

Otherwise try building in a clean chroot, `paru` has  the `--chroot` option for that. Or you could download the built package from chaotic aur.

**Comment by guillaume-bonnefoy** [comment]
Using `paru` with `--chroot` solved it for me ! Thanks !!!
