### ISSUE TITLE
Type generation fails

### ISSUE THREAD

**Issue by yashranjan1** [Aylur/ags#617]
Sorry if this is a stupid question but, when I init the type generation fails, im not sure why

```
ags init
error: type generation failed, try running
/usr/bin/npx -y @ts-for-gir/cli@4.0.0-beta.15 generate * --ignoreVersionConflicts --outdir /home/yash/.config/ags/@girs -g /usr/local/share/gir-1.0 -g /usr/share/gir-1.0 -g /usr/share/*/gir-1.0 -g gir-1.0
```

When I try the recommended command it gives me the following error 

```
/usr/bin/npx -y @ts-for-gir/cli@4.0.0-beta.15 generate * --ignoreVersionConflicts --outdir /home/yash/.config/ags/@girs -g /usr/local/share/gir-1.0 -g /usr/share/gir-1.0 -g /usr/share/*/gir-1.0 -g gir-1.0
Adding generics...
ts-for-gir generate [modules..]

Generates Typescript type definition .d.ts files from GIR for GJS

Options:
      --version                 Show version number                    [boolean]
      --help                    Show help                              [boolean]
      --modules                 GIR modules to load, e.g. 'Gio-2.0'. Accepts mul
                                tiple modules           [array] [default: ["*"]]
  -g, --girDirectories          GIR directories
  [array] [default: ["/usr/local/share/gir-1.0","/usr/share/gir-1.0","/usr/share
  /*/gir-1.0","/usr/share/gnome-shell","/usr/share/gnome-shell/gir-1.0","/usr/li
        b64/mutter-*","/usr/lib/mutter-*","/usr/lib/x86_64-linux-gnu/mutter-*"]]
      --root                    Root directory of your project
                                        [string] [default: "/home/yash/.config"]
  -o, --outdir                  Directory to output to
                                                  [string] [default: "./@types"]
  -i, --ignore                  Modules that should be ignored
                                                           [array] [default: []]
  -v, --verbose                 Switch on/off the verbose mode
                                                       [string] [default: false]
      --ignoreVersionConflicts  Skip prompts for library version selection when
                                multiple versions are detected
                                                       [string] [default: false]
  -p, --print                   Print the output to console and create no files
                                                       [string] [default: false]
      --configName              Specify a custom name for the configuration file
                                          [string] [default: ".ts-for-girrc.js"]
  -d, --noNamespace             Do not export all symbols for each module as a n
                                amespace               [string] [default: false]
  -n, --noComments              Do not generate documentation comments
                                                       [string] [default: false]
      --promisify               Generate promisified functions for async/finish
                                calls                   [string] [default: true]
      --npmScope                Scope of the generated NPM packages
                                                     [string] [default: "@girs"]
      --workspace               Uses the workspace protocol for the generated pa
                                ckages which can be used with package managers l
                                ike Yarn and PNPM      [string] [default: false]
      --onlyVersionPrefix       Only use the version prefix for the ambient modu
                                le exports. This is useful if, for whatever reas
                                on, you want to use different library versions o
                                f the same library in your project.
                                                       [string] [default: false]
      --noPrettyPrint           Do not prettify the generated types
                                                       [string] [default: false]
      --noAdvancedVariants      Disable GLib.Variant class with string parsing
                                                        [string] [default: true]
      --package                 Generate the typescript types with package.json
                                support                [string] [default: false]

Examples:
  ts-for-gir generate                       Run 'ts-for-gir generate' in your gj
                                            s project to generate typings for yo
                                            ur project, pass the gir modules you
                                             need for your project
  ts-for-gir generate Gtk*                  You can also use wild cards
  ts-for-gir generate '*'                   If you want to parse all of your loc
                                            ally installed gir modules run
  ts-for-gir generate --configName='.ts-fo  Use a special config file
  r-gir.gtk4.rc.js
  ts-for-gir generate --ignore=Gtk-4.0 xra  Generate .d.ts. files but not for Gt
  ndr-1.3                                   k-4.0 and xrandr-1.3

Error: Could not generify Gtk 4.0
    at file:///home/yash/.npm/_npx/9947fdcb15df8564/node_modules/@ts-for-gir/lib/lib/generics/generify.js:17:19
    at generify (file:///home/yash/.npm/_npx/9947fdcb15df8564/node_modules/@ts-for-gir/lib/lib/generics/generify.js:25:5)
    at DependencyManager.transform (file:///home/yash/.npm/_npx/9947fdcb15df8564/node_modules/@ts-for-gir/lib/lib/gir/registry.js:105:9)
    at GenerationHandler.start (file:///home/yash/.npm/_npx/9947fdcb15df8564/node_modules/@ts-for-gir/cli/lib/generation-handler.js:35:18)
    at async Object.handler (file:///home/yash/.npm/_npx/9947fdcb15df8564/node_modules/@ts-for-gir/cli/lib/commands/generate.js:34:5)
```
Im not really sure whats going here

**Comment by Aylur** [comment]
This usually means you don't have the gtk4 gir file installed.
What distro are you on?

**Comment by yashranjan1** [comment]
arch

**Comment by rogtino** [comment]
I'm currently using nixos.Same error happened here:
```
󰯉 ags types
error: type generation failed, try running
/nix/store/jz54v1m0ldqivx5i45q8i05pz5clf842-nodejs-20.18.0/bin/npx -y @ts-for-gir/cli@4.0.0-beta.15 generate * --ignoreVersionConflicts --outdir /home/gus/.config/ags/@girs -g /usr/local/share/gir-1.0 -g /usr/share/gir-1.0 -g /usr/share/*/gir-1.0 -g /nix/store/slm7mb2626vbl9qwq9cgp1ix6szcyqvw-gtk+3-3.24.43-dev/share/gir-1.0 -g /nix/store/59knjxjaqd279yp8z8miw2kis2szql9n-at-spi2-core-2.54.0-dev/share/gir-1.0 -g /nix/store/1hhi03gg5jdb2fa5gb9ncklziczax741-glib-2.82.1-dev/share/gir-1.0 -g /nix/store/wmbg435clgdlqn4rrn8h5f4jhmhbk24f-gdk-pixbuf-2.42.12-dev/share/gir-1.0 -g /nix/store/h42324qxqnmmmpjg3skvvmllr1l75cma-gsettings-desktop-schemas-47.1/share/gir-1.0 -g /nix/store/774vgpw939f69xb47f2wz31j6di094bp-pango-1.54.0-dev/share/gir-1.0 -g /nix/store/sv5fvv7pimim1z48yyy4fs0amr93qg4q-harfbuzz-9.0.0-dev/share/gir-1.0 -g /nix/store/qrwgj7jhyazhs1kgr61y9k48v4dljxjb-librsvg-2.58.3-dev/share/gir-1.0 -g /nix/store/9qrx21qdxh9vlnmg4hzsh3saiig54q3q-gobject-introspection-wrapped-1.82.0-dev/share/gir-1.0 -g /nix/store/qrwgj7jhyazhs1kgr61y9k48v4dljxjb-librsvg-2.58.3-dev/share/gir-1.0 -g /nix/store/1hhi03gg5jdb2fa5gb9ncklziczax741-glib-2.82.1-dev/share/gir-1.0 -g /nix/store/wmbg435clgdlqn4rrn8h5f4jhmhbk24f-gdk-pixbuf-2.42.12-dev/share/gir-1.0 -g /nix/store/slm7mb2626vbl9qwq9cgp1ix6szcyqvw-gtk+3-3.24.43-dev/share/gir-1.0 -g /nix/store/59knjxjaqd279yp8z8miw2kis2szql9n-at-spi2-core-2.54.0-dev/share/gir-1.0 -g /nix/store/h42324qxqnmmmpjg3skvvmllr1l75cma-gsettings-desktop-schemas-47.1/share/gir-1.0 -g /nix/store/774vgpw939f69xb47f2wz31j6di094bp-pango-1.54.0-dev/share/gir-1.0 -g /nix/store/sv5fvv7pimim1z48yyy4fs0amr93qg4q-harfbuzz-9.0.0-dev/share/gir-1.0 -g /nix/store/4x4lqw85ljkg0x3qx0fxiq49fcjb4l5l-gobject-introspection-1.82.0-dev/share/gir-1.0 -g /nix/store/yw3rnyycd5avw59pczzlainzw954x6sr-astal-0.1.0-dev/share/gir-1.0 -g /nix/store/3smm6wfkc7vkc87lykpgpqq431sdq5sh-astal-3.0.0-dev/share/gir-1.0 -g /nix/store/7mjw24p0xfm45vcm04dxlmfydg00c3jw-gtk-layer-shell-0.9.0-dev/share/gir-1.0 -g /nix/store/3m08jxm3d356kksnb149p13wgdqnq23r-astal-4.0.0-dev/share/gir-1.0 -g /nix/store/k887w7d4qwd9n1lmnk4yblwd11mv5vak-gtk4-4.16.3-dev/share/gir-1.0 -g /nix/store/cnsg6r87wm9rc3v2c757kd0c96adb358-graphene-1.10.8-dev/share/gir-1.0 -g /nix/store/z5yzpa7h7iq4712akdvb14cjl3rs5sqi-gtk4-layer-shell-1.0.4-dev/share/gir-1.0
```

**Comment by pomeluce** [comment]
> This usually means you don't have the gtk4 gir file installed. What distro are you on?

I also encountered this problem. I am also using archlinux and have installed gtk4 dependencies. Is there any solution?

**Comment by iCultureBud** [comment]
I have the exact same error after installing `aylurs-gtk-shell-git` on Arch and running `ags init`.

**Comment by yashranjan1** [comment]
> Edit: ags run seems to work.

Ags run works because type generation is not essential for the widgets to work. Types are useful for LSP, makes writing your config a lot easier to debug.

**Comment by OBLIXi-ON** [comment]
They recommend command doesn't work for me either. It's showing `zsh; no matches found: /usr/share/*/gir-1.0`. `ags run` doesn't work either.

**Comment by yashranjan1** [comment]
> npx -y @ts-for-gir/cli generate --ignoreVersionConflicts --outdir <YOUR-@girs-PATH> -g /usr/share/gir-1.0/

Tried this and got another error 

```
Error: Failed to import Vulkan in GstVulkan, not installed or accessible.
    at GirModule.assertInstalledImport (file:///home/yash/.npm/_npx/4001ac8ae3bf4948/node_modules/@ts-for-gir/lib/lib/gir-module.js:279:19)
    at IntrospectedRecord.isSimpleType (file:///home/yash/.npm/_npx/4001ac8ae3bf4948/node_modules/@ts-for-gir/lib/lib/gir/class.js:821:45)
    at file:///home/yash/.npm/_npx/4001ac8ae3bf4948/node_modules/@ts-for-gir/lib/lib/gir/class.js:851:54
    at Array.every (<anonymous>)
    at IntrospectedRecord.isSimple (file:///home/yash/.npm/_npx/4001ac8ae3bf4948/node_modules/@ts-for-gir/lib/lib/gir/class.js:851:38)
    at file:///home/yash/.npm/_npx/4001ac8ae3bf4948/node_modules/@ts-for-gir/lib/lib/validators/class.js:111:84
    at Array.filter (<anonymous>)
    at removeComplexFields (file:///home/yash/.npm/_npx/4001ac8ae3bf4948/node_modules/@ts-for-gir/lib/lib/validators/class.js:98:31)
    at chainVisitors (file:///home/yash/.npm/_npx/4001ac8ae3bf4948/node_modules/@ts-for-gir/lib/lib/validators/class.js:208:23)
    at ClassVisitor.visitClass (file:///home/yash/.npm/_npx/4001ac8ae3bf4948/node_modules/@ts-for-gir/lib/lib/validators/class.js:213:28)
```

Either way i think this is something ags needs to address. If this was a one off thing that only i faced it would make sense to find my own fix, but the fact that so many people are facing this probably means that installing ags does not guarantee you have everything you need to develop with it installed and ready to use. Hope this can be addressed soon!

**Comment by RewardedIvan** [comment]
I had the same issue as well, but after a bit of thinking I figured this might have something to do with astal and then I realized i never installed astal or anything and just assumed it came with ags, but after running
```bash
yay -S libastal-io-git libastal-git
```
fixed it, but this should probably be in the ags documentation

**Comment by The-Lost-Light** [comment]
libastal-io-git libastal-git is required in ags in AUR(libastal-meta)
I install both two but still have this problem

**Comment by vnva** [comment]
I had same issue

```
npx @ts-for-gir/cli list 
```

This command prints me:

```
Dependencies not found:
- cairo-1.0
- freetype2-2.0
- xlib-2.0
- xft-2.0
- fontconfig-2.0
- libxml2-2.0
- Vulkan-1.0
- DBus-1.0
```

But most of these dependencies are installed in the system.

**Comment by kotontrion** [comment]
@vnva thanks, that was really helpful. Those files are provided by the `gobject-introspection` package. I thought gjs depends on it so it should be installed, but its only a make dependency. So this should be added as a dependency to AGS, I will do so later.

**Comment by vnva** [comment]
@kotontrion thanks, yes, that was the problem, after installing this package I was able to initialize the project using `ags init`.

**Comment by iCultureBud** [comment]
@vnva Thank you - after installing those packages `ags types` run through without problems. :)

**Comment by JohnOberhauser** [comment]
This didn't work for me when I had my config in a custom directory.  I had to move it to `./config/ags`

**Comment by ArtemChandragupta** [comment]
For me on NixOS this solution does not work when my ags config is in my nixos configuration.

**Comment by agentx3** [comment]
I am also on NixOS. I diagnosed the issue by using the `list` subcommand of `@ts-for-gir/cli@4.0.0-beta.19` while passing in the gir directories ( same `-g` flags as the recommended `generate` command).

I resolved my issue by adding `graphene` and `gtk4` into the `extraPackages` of ags, so it possibly might be worth adding those into buildInputs as well

**Comment by IIlllllII** [comment]
> This usually means you don't have the gtk4 gir file installed. What distro are you on?

Today, I also encountered this issue on `Fedora` 42, and resolved it by installing `gtk4-devel`.
 
So, if I don't use `gtk4`, can I ignore it?
Otherwise, would you consider updating the [docs](https://aylur.github.io/astal/guide/getting-started/installation))

**Comment by IIlllllII** [comment]
> This usually means you don't have the gtk4 gir file installed. What distro are you on?

Today, I encountered the same issue on `Fedora` 42, and resolved it by installing `gtk4-devel`.
 
So, if I'm not using `gtk4`, can I just ignore it?
Otherwise, would you consider updating the [docs](https://aylur.github.io/astal/guide/getting-started/installation)?

**Comment by Perodactyl** [comment]
I just found the solution to my issue. Some files in my NPM cache were owned by root, and it was trying to overwrite them.

**Comment by kotontrion** [comment]
By default AGS will generate types for all installed gir libs, which in many cases is not necessary. You can specify a pattern for which libs to generate the types. Eg running `ags types "Astal*"` is probably sufficient in most cases. The types for other libs can still be generated by running it again with a different pattern later.

Maybe the default should change to a two step system. In the first step generate types for things that are actually needed for ags, eg Gtk, Gdk, Gtk layer shell, the astal libs. The second step generates the rest. Only the first step should fail, the second only print warnings. This would prevent this issue somewhat, as it won't be affected as much by random libs. Eg librest is not used by ags, astal, or any of its dependencies.

**Comment by unai-ndz** [comment]
Got this recently:

```bash
> ags types -v
executing: /usr/bin/npx -y @ts-for-gir/cli@4.0.0-beta.19 generate * --ignoreVersionConflicts --outdir .config/ags/@girs -g /usr/local/share/gir-1.0 -g /usr/share/gir-1.0 -g /usr/share/*/gir-1.0 -g
node:internal/modules/typescript:183
    throw new ERR_UNSUPPORTED_NODE_MODULES_TYPE_STRIPPING(filename);
          ^

Error [ERR_UNSUPPORTED_NODE_MODULES_TYPE_STRIPPING]: Stripping types is currently unsupported for files under node_modules, for "file://.npm/_npx/24f50c9ed13719e6/node_modules/@ts-for-gir/lib/src/index.ts"
```


Opened this `.npm/_npx/24f50c9ed13719e6/node_modules/@ts-for-gir/lib/package.json` which showed:
```json
{
  "name": "@ts-for-gir/lib",
  "version": "4.0.0-beta.38",
```
